version: '3'

services:
  db:
    image: usmysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: inventarios
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - /home/juank/Descargas/mysql_data/:/var/lib/mysql/
    ports:
      - "3306:3306"
  web:
    # image: php:7.2.2-apache
    image: myphp
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true